require('dotenv').config();
const express=require('express'), http=require('http'), path=require('path'), crypto=require('crypto');
const bcrypt=require('bcryptjs'), jwt=require('jsonwebtoken'), cookieParser=require('cookie-parser');
const Database=require('better-sqlite3'), rateLimit=require('express-rate-limit'), nodemailer=require('nodemailer');
const {Server}=require('socket.io');
const app=express(), server=http.createServer(app), io=new Server(server);
app.set('trust proxy', 1);
const PORT=+process.env.PORT||3000, SECRET=process.env.JWT_SECRET||'change-me';
const DEMO_MODE=String(process.env.DEMO_MODE||'false').toLowerCase()==='true';
const PUBLIC_URL=(process.env.PUBLIC_URL||'').replace(/\/$/,'');
const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'admin@fintrada.local').toLowerCase();
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'ChangeMe_12345!';
require('fs').mkdirSync(path.join(__dirname,'data'),{recursive:true});
const db=new Database(path.join(__dirname,'data/fintrada.db')); db.pragma('journal_mode=WAL');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');next()});
app.use(express.json({limit:'100kb'})); app.use(express.urlencoded({extended:true})); app.use(cookieParser());
app.use(express.static(path.join(__dirname,'public')));
const limiter=rateLimit({windowMs:15*60*1000,max:60});

db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT,password_hash TEXT NOT NULL,role TEXT DEFAULT 'user',verified INTEGER DEFAULT 0,verify_token TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS wallets(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,currency TEXT,balance REAL DEFAULT 0,UNIQUE(user_id,currency),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,type TEXT,currency TEXT,amount REAL,status TEXT,reference TEXT UNIQUE,description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,currency TEXT,amount REAL,bank_name TEXT,account_name TEXT,account_number TEXT,status TEXT DEFAULT 'PENDING',admin_note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,processed_at TEXT);
CREATE TABLE IF NOT EXISTS investments(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,opportunity TEXT,sector TEXT,currency TEXT,principal REAL,target_rate REAL DEFAULT 10,term_months INTEGER DEFAULT 12,status TEXT DEFAULT 'ACTIVE',created_at TEXT DEFAULT CURRENT_TIMESTAMP,maturity_date TEXT);
CREATE TABLE IF NOT EXISTS treasury(id INTEGER PRIMARY KEY AUTOINCREMENT,currency TEXT,type TEXT,amount REAL,description TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,action TEXT,target TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);

function ref(p){return p+'-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function token(u){return jwt.sign({id:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'2h'})}
function auth(req,res,next){try{let t=req.cookies.fintrada_token||req.headers.authorization?.replace('Bearer ','');if(!t)throw 0;req.user=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({error:'Authentication required.'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Administrator access required.'});next()}
function wallets(id){for(const c of ['NGN','USD'])db.prepare('INSERT OR IGNORE INTO wallets(user_id,currency,balance) VALUES(?,?,0)').run(id,c);return db.prepare('SELECT currency,balance FROM wallets WHERE user_id=?').all(id)}
function seedDemoWallets(id){if(!DEMO_MODE)return;db.prepare("UPDATE wallets SET balance=CASE currency WHEN 'NGN' THEN 1000000 ELSE 1000 END WHERE user_id=?").run(id)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function mailVerify(email,name,url){if(!process.env.SMTP_HOST){console.log('\n[FINTRADA DEMO EMAIL] '+email+' => '+url+'\n');return}const tr=nodemailer.createTransport({host:process.env.SMTP_HOST,port:+(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await tr.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:email,subject:'Verify your FINTRADA account',html:`<h2>Welcome to FINTRADA, ${esc(name)}</h2><p>Verify your account: <a href="${url}">Verify email</a></p>`})}
const existing=db.prepare('SELECT id FROM users WHERE email=?').get(ADMIN_EMAIL);if(!existing){let h=bcrypt.hashSync(ADMIN_PASSWORD,12);let id=db.prepare("INSERT INTO users(full_name,email,password_hash,role,verified) VALUES(?,?,?,?,1)").run('FINTRADA Administrator',ADMIN_EMAIL,h,'admin').lastInsertRowid;wallets(id);console.log('Admin: '+ADMIN_EMAIL)}
if(DEMO_MODE){const demoEmail=(process.env.DEMO_EMAIL||'demo@fintrada.test').toLowerCase();const demoPassword=process.env.DEMO_PASSWORD||'Demo_12345!';let du=db.prepare('SELECT id FROM users WHERE email=?').get(demoEmail);if(!du){let h=bcrypt.hashSync(demoPassword,12);let id=db.prepare("INSERT INTO users(full_name,email,password_hash,role,verified) VALUES(?,?,?,?,1)").run('FINTRADA Demo User',demoEmail,h,'user').lastInsertRowid;wallets(id);seedDemoWallets(id);console.log('Demo: '+demoEmail+' / '+demoPassword)}else{seedDemoWallets(du.id)}}

app.post('/api/auth/register',limiter,async(req,res)=>{let n=String(req.body.fullName||'').trim(),e=String(req.body.email||'').trim().toLowerCase(),p=String(req.body.phone||''),pw=String(req.body.password||'');if(!n||!e||pw.length<8)return res.status(400).json({error:'Name, email and password of 8+ characters are required.'});if(db.prepare('SELECT id FROM users WHERE email=?').get(e))return res.status(409).json({error:'Email already registered.'});let hash=await bcrypt.hash(pw,12),v=crypto.randomBytes(32).toString('hex'),id=db.prepare('INSERT INTO users(full_name,email,phone,password_hash,verify_token) VALUES(?,?,?,?,?)').run(n,e,p,hash,v).lastInsertRowid;wallets(id);let url=`${PUBLIC_URL||`${req.protocol}://${req.get('host')}`}/api/auth/verify?token=${v}`;if(DEMO_MODE){db.prepare('UPDATE users SET verified=1,verify_token=NULL WHERE id=?').run(id)}else await mailVerify(e,n,url);res.json({success:true,message:'Account created. Check your email for verification.'})});
app.get('/api/auth/verify',(req,res)=>{let u=db.prepare('SELECT id FROM users WHERE verify_token=?').get(String(req.query.token||''));if(!u)return res.status(400).send('Invalid verification link.');db.prepare('UPDATE users SET verified=1,verify_token=NULL WHERE id=?').run(u.id);res.redirect('/?verified=1')});
app.post('/api/auth/login',limiter,async(req,res)=>{let e=String(req.body.email||'').trim().toLowerCase(),pw=String(req.body.password||''),u=db.prepare('SELECT * FROM users WHERE email=?').get(e);if(!u||!(await bcrypt.compare(pw,u.password_hash)))return res.status(401).json({error:'Invalid email or password.'});if(!u.verified)return res.status(403).json({error:'Please verify your email first.'});res.cookie('fintrada_token',token(u),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7200000});res.json({success:true})});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('fintrada_token');res.json({success:true})});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'FINTRADA',demo:DEMO_MODE}));
app.get('/api/config',(req,res)=>res.json({demo:DEMO_MODE,demoEmail:DEMO_MODE?(process.env.DEMO_EMAIL||'demo@fintrada.test'):null}));
app.get('/api/me',auth,(req,res)=>{let u=db.prepare('SELECT id,full_name,email,phone,role,verified,created_at FROM users WHERE id=?').get(req.user.id);res.json({user:u,wallets:wallets(u.id)})});

let markets=[['XAGR','Xtra Agro Growth','Share','NGN',245.20,4.82],['XMOB','Nova Mobility','Share','NGN',182.40,2.31],['XEDU','EduCore Systems','Share','NGN',96.50,5.17],['XLOG','Prime Logistics','Share','NGN',311.80,1.64],['XGRN','GreenGrid Energy','Share','NGN',128.10,-1.42],['XDC','Xtra Digital Coin','Coin','USD',1.84,6.21],['NVC','NovaChain','Coin','USD',0.74,3.12],['AGRX','AgriX Token','Coin','USD',2.31,-0.82]].map(x=>({symbol:x[0],name:x[1],type:x[2],currency:x[3],price:x[4],change:x[5]}));
app.get('/api/markets',(req,res)=>res.json({demo:true,notice:'Synthetic demonstration market data — not live exchange prices.',assets:markets}));
setInterval(()=>{markets=markets.map(a=>{let d=(Math.random()-.46)*1.3;return {...a,price:+Math.max(.01,a.price*(1+d/100)).toFixed(a.currency==='NGN'?2:4),change:+Math.max(-15,Math.min(15,a.change+d)).toFixed(2)}});io.emit('market:update',markets)},5000);
app.get('/api/investments',(req,res)=>res.json({targetAnnualRate:10,notice:'Illustrative target only; not guaranteed.',opportunities:[['agri','FINTRADA Agriculture Growth','Agriculture',10000],['mob','FINTRADA Mobility','Transportation',10000],['edu','FINTRADA Education','Education',5000],['tech','FINTRADA Digital Growth','Technology',10000]].map(x=>({id:x[0],name:x[1],sector:x[2],minimum:x[3],term:'12 months',risk:'Moderate',description:'Illustrative sector allocation for the prototype.'}))}));
app.get('/api/portfolio',auth,(req,res)=>res.json({wallets:wallets(req.user.id),investments:db.prepare('SELECT * FROM investments WHERE user_id=? ORDER BY created_at DESC').all(req.user.id),transactions:db.prepare('SELECT * FROM transactions WHERE user_id=? ORDER BY created_at DESC LIMIT 30').all(req.user.id)}));
app.post('/api/deposits',auth,(req,res)=>{let c=String(req.body.currency||'').toUpperCase(),a=+req.body.amount;if(!['NGN','USD'].includes(c)||!(a>0))return res.status(400).json({error:'Valid currency and amount required.'});let r=ref('DEP');db.prepare('INSERT INTO transactions(user_id,type,currency,amount,status,reference,description) VALUES(?,?,?,?,?,?,?)').run(req.user.id,'DEPOSIT',c,a,'PENDING',r,'Demo deposit request');res.json({success:true,reference:r,message:'Deposit request recorded as pending. Production payments require verified provider webhooks.'})});
app.post('/api/investments',auth,(req,res)=>{let c=String(req.body.currency||'').toUpperCase(),a=+req.body.amount,opp=String(req.body.opportunity||''),sector=String(req.body.sector||'');let w=db.prepare('SELECT balance FROM wallets WHERE user_id=? AND currency=?').get(req.user.id,c);if(!['NGN','USD'].includes(c)||!(a>0)||!w||w.balance<a)return res.status(400).json({error:'Insufficient wallet balance or invalid details.'});let m=new Date();m.setMonth(m.getMonth()+12);db.transaction(()=>{db.prepare('UPDATE wallets SET balance=balance-? WHERE user_id=? AND currency=?').run(a,req.user.id,c);db.prepare('INSERT INTO investments(user_id,opportunity,sector,currency,principal,target_rate,term_months,maturity_date) VALUES(?,?,?,?,?,?,?,?,?)').run(req.user.id,opp,sector,c,a,10,12,m.toISOString());db.prepare('INSERT INTO transactions(user_id,type,currency,amount,status,reference,description) VALUES(?,?,?,?,?,?,?)').run(req.user.id,'INVESTMENT',c,a,'COMPLETED',ref('INV'),'Investment '+opp)})();res.json({success:true,message:'Investment recorded in demo ledger.'})});
app.post('/api/withdrawals',auth,(req,res)=>{let c=String(req.body.currency||'').toUpperCase(),a=+req.body.amount,w=db.prepare('SELECT balance FROM wallets WHERE user_id=? AND currency=?').get(req.user.id,c);if(!['NGN','USD'].includes(c)||!(a>0)||!w||w.balance<a)return res.status(400).json({error:'Insufficient available balance or invalid details.'});let id=db.transaction(()=>{db.prepare('UPDATE wallets SET balance=balance-? WHERE user_id=? AND currency=?').run(a,req.user.id,c);let id=db.prepare('INSERT INTO withdrawals(user_id,currency,amount,bank_name,account_name,account_number) VALUES(?,?,?,?,?,?)').run(req.user.id,c,a,String(req.body.bankName||''),String(req.body.accountName||''),String(req.body.accountNumber||'')).lastInsertRowid;db.prepare('INSERT INTO transactions(user_id,type,currency,amount,status,reference,description) VALUES(?,?,?,?,?,?,?)').run(req.user.id,'WITHDRAWAL',c,a,'PENDING',ref('WDR'),'Withdrawal awaiting admin approval');return id})();res.json({success:true,withdrawalId:id,message:'Withdrawal submitted for administrator approval.'})});

app.get('/api/admin/overview',auth,admin,(req,res)=>{res.json({users:db.prepare("SELECT COUNT(*) n FROM users WHERE role='user'").get().n,verified:db.prepare("SELECT COUNT(*) n FROM users WHERE role='user' AND verified=1").get().n,pendingWithdrawals:db.prepare("SELECT COUNT(*) n FROM withdrawals WHERE status='PENDING'").get().n,pendingDeposits:db.prepare("SELECT COUNT(*) n FROM transactions WHERE type='DEPOSIT' AND status='PENDING'").get().n})});
app.get('/api/admin/deposits',auth,admin,(req,res)=>res.json(db.prepare("SELECT t.*,u.full_name,u.email FROM transactions t JOIN users u ON u.id=t.user_id WHERE t.type='DEPOSIT' ORDER BY CASE WHEN t.status='PENDING' THEN 0 ELSE 1 END,t.created_at DESC LIMIT 100").all()));
app.post('/api/admin/deposits/:id/approve',auth,admin,(req,res)=>{let t=db.prepare("SELECT * FROM transactions WHERE id=? AND type='DEPOSIT'").get(+req.params.id);if(!t||t.status!=='PENDING')return res.status(400).json({error:'Deposit not found or already processed.'});db.transaction(()=>{db.prepare('UPDATE wallets SET balance=balance+? WHERE user_id=? AND currency=?').run(t.amount,t.user_id,t.currency);db.prepare("UPDATE transactions SET status='COMPLETED',description=? WHERE id=?").run(String(req.body.note||'Deposit approved by administrator'),t.id);db.prepare('INSERT INTO audit(admin_id,action,target,details) VALUES(?,?,?,?)').run(req.user.id,'APPROVE_DEPOSIT','transaction:'+t.id,JSON.stringify({amount:t.amount,currency:t.currency,user_id:t.user_id}))})();res.json({success:true,message:'Deposit approved and wallet credited.'})});
app.post('/api/admin/deposits/:id/reject',auth,admin,(req,res)=>{let t=db.prepare("SELECT * FROM transactions WHERE id=? AND type='DEPOSIT'").get(+req.params.id);if(!t||t.status!=='PENDING')return res.status(400).json({error:'Deposit not found or already processed.'});db.transaction(()=>{db.prepare("UPDATE transactions SET status='REJECTED',description=? WHERE id=?").run(String(req.body.note||'Deposit rejected by administrator'),t.id);db.prepare('INSERT INTO audit(admin_id,action,target,details) VALUES(?,?,?,?)').run(req.user.id,'REJECT_DEPOSIT','transaction:'+t.id,String(req.body.note||''))})();res.json({success:true,message:'Deposit rejected.'})});
app.get('/api/admin/withdrawals',auth,admin,(req,res)=>res.json(db.prepare("SELECT w.*,u.full_name,u.email FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY CASE WHEN w.status='PENDING' THEN 0 ELSE 1 END,w.created_at DESC LIMIT 100").all()));
app.post('/api/admin/withdrawals/:id/approve',auth,admin,(req,res)=>{let w=db.prepare('SELECT * FROM withdrawals WHERE id=?').get(+req.params.id);if(!w||w.status!=='PENDING')return res.status(400).json({error:'Withdrawal not found or already processed.'});db.transaction(()=>{db.prepare("UPDATE withdrawals SET status='APPROVED',processed_at=CURRENT_TIMESTAMP,admin_note=? WHERE id=?").run(String(req.body.note||'Approved'),w.id);db.prepare('INSERT INTO transactions(user_id,type,currency,amount,status,reference,description) VALUES(?,?,?,?,?,?,?)').run(w.user_id,'WITHDRAWAL_PAYOUT',w.currency,w.amount,'APPROVED',ref('PAY'),'Approved for payout');db.prepare('INSERT INTO audit(admin_id,action,target,details) VALUES(?,?,?,?)').run(req.user.id,'APPROVE_WITHDRAWAL','withdrawal:'+w.id,JSON.stringify(w))})();res.json({success:true,message:'Withdrawal approved. A real payout provider must execute the bank transfer in production.'})});
app.post('/api/admin/withdrawals/:id/reject',auth,admin,(req,res)=>{let w=db.prepare('SELECT * FROM withdrawals WHERE id=?').get(+req.params.id);if(!w||w.status!=='PENDING')return res.status(400).json({error:'Withdrawal not found or already processed.'});db.transaction(()=>{db.prepare('UPDATE wallets SET balance=balance+? WHERE user_id=? AND currency=?').run(w.amount,w.user_id,w.currency);db.prepare("UPDATE withdrawals SET status='REJECTED',processed_at=CURRENT_TIMESTAMP,admin_note=? WHERE id=?").run(String(req.body.note||'Rejected'),w.id);db.prepare('INSERT INTO transactions(user_id,type,currency,amount,status,reference,description) VALUES(?,?,?,?,?,?,?)').run(w.user_id,'WITHDRAWAL_RELEASE',w.currency,w.amount,'COMPLETED',ref('REL'),'Rejected withdrawal returned to wallet');db.prepare('INSERT INTO audit(admin_id,action,target,details) VALUES(?,?,?,?)').run(req.user.id,'REJECT_WITHDRAWAL','withdrawal:'+w.id,String(req.body.note||''))})();res.json({success:true,message:'Withdrawal rejected and funds returned to wallet.'})});
app.get('/api/admin/users',auth,admin,(req,res)=>res.json(db.prepare('SELECT id,full_name,email,phone,role,verified,created_at FROM users ORDER BY created_at DESC LIMIT 200').all()));
app.get('/api/admin/treasury',auth,admin,(req,res)=>res.json(db.prepare('SELECT * FROM treasury ORDER BY created_at DESC LIMIT 200').all()));
app.post('/api/admin/treasury',auth,admin,(req,res)=>{let c=String(req.body.currency||'').toUpperCase(),t=String(req.body.type||'').toUpperCase(),a=+req.body.amount,d=String(req.body.description||'');if(!['NGN','USD'].includes(c)||!['DEPOSIT','WITHDRAWAL'].includes(t)||!(a>0))return res.status(400).json({error:'Invalid treasury entry.'});db.prepare('INSERT INTO treasury(currency,type,amount,description,created_by) VALUES(?,?,?,?,?)').run(c,t,a,d,req.user.id);db.prepare('INSERT INTO audit(admin_id,action,target,details) VALUES(?,?,?,?)').run(req.user.id,'TREASURY_'+t,'treasury',JSON.stringify({c,a,d}));res.json({success:true})});
app.get('/api/admin/audit',auth,admin,(req,res)=>res.json(db.prepare('SELECT a.*,u.full_name admin_name FROM audit a LEFT JOIN users u ON u.id=a.admin_id ORDER BY a.created_at DESC LIMIT 200').all()));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
server.listen(PORT,()=>console.log(`FINTRADA running on http://localhost:${PORT}`));
